Printing SUCCESS/FAILURE only makes sense in the context of a run.

diff --git a/bin/ci b/bin/ci
--- a/bin/ci
+++ b/bin/ci
@@ -54,6 +54,14 @@ case "$subcommand" in
       echo "Directory '$project' does not exist."
       exit 1
     fi
+
+    if [ "$status" -eq 0 ]; then
+      echo "SUCCESS"
+      exit 0
+    else
+      echo "FAILURE"
+      exit 1
+    fi
     ;;
 
   init)
@@ -83,10 +91,3 @@ case "$subcommand" in
     ;;
 esac
 
-if [ "$status" -eq 0 ]; then
-  echo "SUCCESS"
-  exit 0
-else
-  echo "FAILURE"
-  exit 1
-fi
